In [2]:
import pandas as pd 
df = pd.read_csv("reklamvesatis.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  gazete  satislar
0  230.1   37.8    69.2      22.1
1   44.5   39.3    45.1      10.4
2   17.2   45.9    69.3       9.3
3  151.5   41.3    58.5      18.5
4  180.8   10.8    58.4      12.9

In [17]:
len(df)

200

In [4]:
# Tahmin için kullanılacak veri (X) ile, tahmini yapılacak olan verinin (y) ayrıştırılması
X = df.drop('satislar', axis=1)
y = df["satislar"]

In [5]:
X.head()

TV  radio  gazete
0  230.1   37.8    69.2
1   44.5   39.3    45.1
2   17.2   45.9    69.3
3  151.5   41.3    58.5
4  180.8   10.8    58.4

In [6]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: satislar, dtype: float64

In [8]:
# pandas dataframe haline getirme
y = df[["satislar"]]

In [9]:
y.head()

satislar
0      22.1
1      10.4
2       9.3
3      18.5
4      12.9

In [10]:
X.head()

TV  radio  gazete
0  230.1   37.8    69.2
1   44.5   39.3    45.1
2   17.2   45.9    69.3
3  151.5   41.3    58.5
4  180.8   10.8    58.4

Verilerin Eğitim ve Test Verisi olarak bölünmesi

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# random_state değeri 1 olarak ayarlanırsa, eğitim ve test için ayrılan veriler sürekli değişir
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 99)

In [14]:
len(X_train)

160

In [16]:
len(X_test)

40

Makine Öğrenmesi Modelinin Kurulması

In [18]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

Modelin Eğitilmesi

In [19]:
model = lm.fit(X_train, y_train)

Yeni verilerle tahmin işleminin yapılması
    

Örnek problem : 30 birim TV, 10 birim Radio, 40 birim Gazete harcaması sonucunda satışlar ne olur.

In [26]:
yeni_veri = [[30],[10],[40]]
yeni_veri

[[30], [10], [40]]

In [27]:
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [28]:
model.predict(yeni_veri)

array([[6.18181031]])

Var olan test verisini kullanarak tahmin işleminin yapılması

In [31]:
# Gerçek değerler veri setindeki ilk 10 değer
y.head(10)

satislar
0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
5       7.2
6      11.8
7      13.2
8       4.8
9      10.6

In [30]:
# İlk on kayıt için tahmin işlemnin yapılması
model.predict(X)[0:10]

array([[20.54159137],
       [12.35990106],
       [12.37795961],
       [17.6155085 ],
       [13.20848464],
       [12.56006616],
       [11.71188738],
       [12.07183086],
       [ 3.69181916],
       [12.501818  ]])

MODEL DEKİ HATALARIN HESAPLANMASI

In [32]:
from sklearn.model_selection import cross_val_score

In [44]:
# Eğitim seti için
egitim_hatası = cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")
egitim_hatası

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [46]:
egitim_hata_ort = np.mean(-egitim_hatası)
egitim_hata_ort

3.3170289742341255

In [49]:
egitim_hata_ort_karakok = np.sqrt(egitim_hata_ort)
egitim_hata_ort_karakok

1.8212712522395245

In [50]:
# Test veri seti için
test_egitim_hatasi = cross_val_score(model, X_test, y_test, cv=10, scoring="neg_mean_squared_error")
test_egitim_hatasi

array([-4.38984219, -3.0979069 , -5.01750896, -2.96824449, -3.03201552,
       -1.69816908, -0.49509029, -1.23755559, -0.14213351, -2.87887471])

In [51]:
test_egitim_hatasi_ort = np.mean(-test_egitim_hatasi)
test_egitim_hatasi_ort

2.495734122608571

In [53]:
test_egitim_hatasi_ort_karekok = np.sqrt(test_egitim_hatasi_ort)
test_egitim_hatasi_ort_karekok

1.5797892652529866

Hata ortalamalarının karaköklerinin mümkün olduğu kadar bir birine yakın olması tercih edilir

Modelin iyileştirilmesi için, Veri Temizleme, Yeni Veri Ekleme, Model Değiştirme gibi işlemler yapılabilir.